// <auto-generated />
namespace Viper.BusinessEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ViperDbContext_v4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ViperDbContext_v4));
        
        string IMigrationMetadata.Id
        {
            get { return "201808121913134_ViperDbContext_v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
